server: 
  port: 9004
spring: 
  application:  
    name: tensquare_article #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 1234
  jpa: 
    database: mysql
    show-sql: true
  redis:
    host: 192.168.200.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
