server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/tensquare_recruit?characterEncoding=utf-8 #useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 1234
  jpa: 
    database: mysql
    show-sql: true
